/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package duplex;

import java.io.File;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        URL fxmlLocation = new File("./src/main/java/duplex/duplex.fxml").getCanonicalFile().toURI().toURL();
        System.out.println("FXML Location: " + fxmlLocation);
        loader.setLocation(fxmlLocation);
        VBox vbox = loader.<VBox>load();

        Scene scene = new Scene(vbox);
        stage.setScene(scene);

        System.out.println("Showing stage");
        stage.show();
    }

    public static void main(String[] args) {
        System.out.println("Launching app!");
        launch();
        System.out.println("App exited");
        System.exit(0);
    }
}
