/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package duplex;

import java.io.File;
import java.net.URL;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        URL fxmlLocation = new File("./src/main/java/duplex/duplex.fxml").getCanonicalFile().toURI().toURL();
        System.out.println(fxmlLocation);
        loader.setLocation(fxmlLocation);
        VBox vbox = loader.<VBox>load();

        Scene scene = new Scene(vbox);
        stage.setScene(scene);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
